// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR3LSNFTjdCYCFkHw5z-1Go54X72WSjwQ',
    appId: '1:282562493768:web:1b93344f7c44c8bf3d877d',
    messagingSenderId: '282562493768',
    projectId: 'food-delivery-app-pk',
    authDomain: 'food-delivery-app-pk.firebaseapp.com',
    storageBucket: 'food-delivery-app-pk.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGhVrgp7hTt63ozgPQY_6iU7hTyXFk2E8',
    appId: '1:282562493768:ios:ed6dee0ae4ea03773d877d',
    messagingSenderId: '282562493768',
    projectId: 'food-delivery-app-pk',
    storageBucket: 'food-delivery-app-pk.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR3LSNFTjdCYCFkHw5z-1Go54X72WSjwQ',
    appId: '1:282562493768:web:0e6d2767ae9884c83d877d',
    messagingSenderId: '282562493768',
    projectId: 'food-delivery-app-pk',
    authDomain: 'food-delivery-app-pk.firebaseapp.com',
    storageBucket: 'food-delivery-app-pk.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGhVrgp7hTt63ozgPQY_6iU7hTyXFk2E8',
    appId: '1:282562493768:ios:ed6dee0ae4ea03773d877d',
    messagingSenderId: '282562493768',
    projectId: 'food-delivery-app-pk',
    storageBucket: 'food-delivery-app-pk.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcyx8sVUHEwQAVMDOetNiq3O6rILUFMss',
    appId: '1:282562493768:android:5873661ea9004ac33d877d',
    messagingSenderId: '282562493768',
    projectId: 'food-delivery-app-pk',
    storageBucket: 'food-delivery-app-pk.firebasestorage.app',
  );
}
